"use client";

import axios from "axios";
import { useState } from "react";
import {
  Shield,
  Boxes,
  ClipboardList,
  GitBranch,
} from "lucide-react";


export default function Home() {

  const [repoUrl, setRepoUrl] = useState("");

  const [loading, setLoading] = useState(false);

  const [report, setReport] = useState<any>(null);

  const analyzeRepository = async () => {

    if (!repoUrl) return;

    setLoading(true);

    try {

      const response = await axios.post(
        `${process.env.NEXT_PUBLIC_API_URL}/analyze-repo`,
        {
          repo_url: repoUrl,
        }
      );

      setReport(response.data);

    } catch (error) {

      console.error(error);

    } finally {

      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-gradient-to-b from-black via-zinc-950 to-zinc-900 text-white p-8">

      <div className="max-w-6xl mx-auto">

        <div className="text-center mb-12">

          <h1 className="text-5xl md:text-6xl font-extrabold mb-4 tracking-tight bg-gradient-to-r from-white to-zinc-500 bg-clip-text text-transparent">
            Hermes Engineering Crew
          </h1>
          <div className="flex justify-center mt-5">
            <div className="p-3 rounded-full border border-zinc-800 bg-zinc-900">
              <GitBranch className="text-zinc-400" size={24} />
            </div>
          </div>
          <p className="text-zinc-400 text-lg">
            Hermes-inspired AI agents collaborating to analyze and improve software repositories
          </p>
          <div className="flex justify-center mt-5">
            <div className="p-3 rounded-full border border-zinc-800 bg-zinc-900">
              <GitBranch className="text-zinc-400" size={24} />
            </div>
          </div>
        </div>

        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 mb-10">

          <div className="flex gap-4">

            <input
              type="text"
              placeholder="Enter GitHub repository URL..."
              value={repoUrl}
              onChange={(e) => setRepoUrl(e.target.value)}
              className="flex-1 bg-zinc-950 border border-zinc-700 rounded-xl px-4 py-3 outline-none"
            />

            <button
              onClick={analyzeRepository}
              disabled={loading}
              className="bg-white hover:bg-zinc-200 transition-all duration-200 text-black px-6 py-3 rounded-xl font-semibold shadow-lg shadow-white/10"
            >
              {loading ? "Analyzing..." : "Analyze"}
            </button>

          </div>
        </div>

        {loading && (

          <div className="grid md:grid-cols-3 gap-6 mb-10">

            <AgentCard
              icon={<Shield />}
              title="Security Agent"
              status="Running..."
            />

            <AgentCard
              icon={<Boxes />}
              title="Architecture Agent"
              status="Running..."
            />

            <AgentCard
              icon={<ClipboardList />}
              title="Planning Agent"
              status="Synthesizing..."
            />

          </div>
        )}

        {report && (


          <div className="grid md:grid-cols-3 gap-6">
            <div className="mb-6">
              <h2 className="text-2xl font-bold">
                Engineering Analysis Report
              </h2>

              <p className="text-zinc-500 mt-1">
                Multi-agent repository analysis generated by Hermes Engineering Crew
              </p>
            </div>

            <ReportCard
              title="Security Report"
              content={report.security_report.summary}
              score={report.security_report.score}
            />

            <ReportCard
              title="Architecture Report"
              content={report.architecture_report.summary}
              score={report.architecture_report.score}
            />

            <ReportCard
              title="Planning Report"
              content={report.planning_report.issues[0].description}
              score={report.planning_report.score}
            />

          </div>
        )}
      </div>
      <footer className="mt-20 text-center text-zinc-600 text-sm">
        Hermes Engineering Crew • Local AI Orchestration with Gemma + Ollama
      </footer>
    </main>
  );
}

function AgentCard({
  icon,
  title,
  status,
}: any) {

  return (
    <div className="bg-zinc-900/80 backdrop-blur border border-zinc-800 rounded-2xl p-6 hover:border-zinc-700 transition-all duration-300">

      <div className="flex items-center gap-3 mb-4">

        <div className="text-green-400">
          {icon}
        </div>

        <h2 className="font-semibold text-lg">
          {title}
        </h2>
      </div>

      <p className="text-zinc-400 animate-pulse">
        {status}
      </p>
    </div>
  );
}

function ReportCard({
  title,
  content,
  score,
}: {
  title: string;
  content: string;
  score?: number;
}) {

  return (
    <div className="bg-zinc-900/80 backdrop-blur border border-zinc-800 rounded-2xl p-6 hover:border-zinc-700 transition-all duration-300">

      <div className="inline-flex items-center px-3 py-1 rounded-full bg-zinc-800 text-xs text-zinc-300 mb-4">
        AI Confidence Score: {score ?? 90}
      </div>

      <h2 className="text-xl font-semibold mb-4">
        {title}
      </h2>

      <p className="text-zinc-300 whitespace-pre-wrap text-sm leading-6">
        {content}
      </p>
    </div>
  );
}